### ISSUE TITLE
Organization and plugins hardcoded

### ISSUE THREAD

**Issue by LarsHoldijk** [RUGSoftEng/2017-Hestia-Server#57] opened 2017-04-12 10:48 UTC
The possible organizations and plug ins are still hard-coded. This should be retrieved somewhere from a configuration file that can easily be updated with new plugins.

**Comment by LarsHoldijk** [comment] 2017-04-12 10:50
I currently have a beta version of an idea ready that we could implement in the next sprint. It uses a configuration file that specifies all information needed for devices and activators. 

This would clean-up the device and activator class but also solve this issue.

**Comment by szijerveld** [comment] 2017-04-13 08:42
Isn't this a duplicate of #31?
I think that either of these should be closed.

**Closed as completed** 2017-05-10 15:16 UTC
